# Generated by Django 5.2.2 on 2025-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.CharField(choices=[('NATIONS_LEAGUE', 'Nations League'), ('CHAMPIONS_LEAGUE', 'Champions League'), ('BUNDESLIGA', 'Bundesliga'), ('PREMIER_LEAGUE', 'Premier League'), ('NHL', 'NHL'), ('DEL', 'Deutsche Eishockey Liga'), ('NBA', 'NBA'), ('BBL', 'Basketball Bundesliga'), ('EUROLEAGUE', 'EuroLeague'), ('WIMBLEDON', 'Wimbledon'), ('ROLAND_GARROS', 'Roland Garros (French Open)')], max_length=50),
        ),
    ]
