# Generated by Django 5.2.2 on 2025-06-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favoriteteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sport'),
            preserve_default=False,
        ),
    ]
