# Generated by Django 5.2.2 on 2025-06-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.match'),
        ),
    ]
